### PR TITLE
Fix #13 Add support for rfc5424 destinations including structured data

### LINKED ISSUE #13: Allow structured data
Allow the inclusion of structured header data to be compatible with packages such as loggly that require auth tokens and similar inside the syslog header:

see https://www.loggly.com/docs/streaming-syslog-without-using-files/ for an example of headers

### PR DESCRIPTION
**Pull request by brycekahle**
Also allows more options to be specified with just the command line URL.

### CODE REVIEW

**Comment by llamashoes** [comment]
@brycekahle 
Can you share your command to get this to work with Loggly? I have tried a few things but without any luck. Thanks - I know this is an older discussion...

**Comment by brycekahle** [comment]
@llamashoes  `rfc5424://logs-01.loggly.com:514?structuredData=<token>@41058`

**Comment by llamashoes** [comment]
@brycekahle 
Awesome - thanks.

**Comment by mostlyjason** [comment]
+1 this looks great!

**Comment by dansowter** [comment]
+1. Awesome

**Comment by dansowter** [comment]
FYI the merge conflict is addressed here - https://github.com/progrium/logspout/pull/36
and here ```docker pull everydayhero/logspout```

**Pull request merged**
